spring:
  application:
    name: ${APP_NAME:upload-service}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

aws:
  s3:
    endpoint: ${AWS_S3_ENDPOINT:http://localhost:9000}
    region: ${AWS_S3_REGION:us-east-1}
    access-key: ${AWS_S3_ACCESS_KEY:testadmin}
    secret-key: ${AWS_S3_SECRET_KEY:testpassword}
    buckets:
      video-input: ${AWS_S3_VIDEO_BUCKET:raw-videos-bucket}
      thumbnail-input: ${AWS_S3_THUMBNAIL_BUCKET:raw-thumbnails-bucket}
      duration: ${AWS_S3_PRESIGNED_DURATION:15}

kafka:
  topic:
    video-uploaded: ${KAFKA_TOPIC_VIDEO_UPLOADED:xtube.video.progress}